spring.datasource.url=jdbc:postgresql://localhost:5432/lab1_db
spring.datasource.username=postgres
spring.datasource.password=2929
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.thymeleaf.cache=false
<properties>
<java.version>21</java.version>
</properties>